# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image
FROM python:3.10-slim

# Set environment variables for email and optional API key
ENV PUBMED_EMAIL=your-email@example.com
# Uncomment and set if you have an API key
ENV PUBMED_API_KEY=your-api-key  

# Set the working directory
WORKDIR /app

# Copy project files
COPY requirements.txt .


# Install dependencies
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

# Define entrypoint
CMD ["python", "streamable_server.py"]
